name: windows

on:
  push:
    branches:
      - main

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.config }} build on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        os: ["windows-2022"]
        python-version: [3.11]
        config: ["Release"]

    steps:
      - uses: actions/checkout@v4

      - name: Timestamp  # Idea from https://tinyurl.com/47wz7vpv
        id: timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=now::${current_date}")

      - name: Configuring Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\.cache
            C:\Users\runneradmin\conda_pkgs_dir
          key:
            ${{ runner.os }}-${{ matrix.config }}-${{ runner.python-version }}-${{ github.ref }}-ccache-${ { steps.timestamp.outputs.now } }
          restore-keys: |
            ${{ runner.os }}-${{ matrix.config }}-${{ runner.python-version }}-${{ github.ref }}-ccache-

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: latest
          auto-activate-base: true
          activate-environment: ''

      - name: Configuring Conda Environment
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          conda install mamba
          mamba install conda-devenv
          conda devenv -e mamba

      - name: Building, Testing & Installing Reaktoro
        shell: cmd
        run: |
          call conda activate reaktoro || goto :eof
          call conda list || goto :eof
          ccache -s || goto :eof
          ccache -z || goto :eof
          mkdir .build && cd .build || goto :eof
          cmake -GNinja .. -DCMAKE_BUILD_TYPE=${{ matrix.config }} || goto :eof
          ninja || goto :eof
          ninja install || goto :eof
          ninja tests || goto :eof
          ninja examples/install || goto :eof
          ccache -s || goto :eof
